### ISSUE TITLE
[Bug]: Cannot see codec frequency

### ISSUE THREAD

**Issue by Maxilos9999** [nuggslet/MGSM2Fix#27] opened 2024-03-05 00:08 UTC
The codec frequency is invisible when this is installed, leading to not being able to save.

**Comment by philipmodig** [comment] 2024-03-07 19:00
I also have this problem, I can't see the codec numbers and I can't see the name of my saves but I can still save.

Workaround: Press down and you can find mei ling codec and save.
For others codec you have to start at a close frequency, and then count every press.

Some examples:
For Meryl codec: call Cambell and after press left 70 times and then call.
For Natasha: Call Master and after press left 28 times and then call
For HAL: Call mey ling and pres right 16 times and then call

**Comment by ShizCalev** [comment] 2024-03-12 09:18
Duplicate of #15

**Closed** 2024-03-17 15:45 UTC
Labels: bug
