### ISSUE TITLE
[Bug]: Codec Numbers do not appear on 1920x1080 internal resolution

### ISSUE THREAD

**Issue by ioletsgo** [nuggslet/MGSM2Fix#32] opened 2024-06-16 12:07 UTC
## Issue Summary:

Internal Resolution set to Enabled causes codec numbers to not appear

## MGSM2Fix & Game Version Number:
MGSM2Fix Version 2.2
Metal Gear Solid Master Collection Version Ver.1.5.0

## Log Files:

CPU - AMD Ryzen 5800X3D
GPU - AMD Radeon 6750X
RAM - 32GB Corsair

## Reproduction:

in [Internal Resolution] set config to this
Enabled = false
Height = 0
Widescreen = true

![20240614161716_1](https://github.com/nuggslet/MGSM2Fix/assets/36903453/9fd93d96-6298-485d-9872-19801c047a64)

**Comment by ioletsgo** [comment] 2024-06-16 12:09
seems to be a duplicate of #15

**Comment by nuggslet** [comment] 2024-12-22 22:54
Duplicate of #15.

**Closed by nuggslet** 2024-12-22 22:54 UTC
Labels: bug
